apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-image
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  params:
  - name: image-name
    description: Name of the image to build
  - name: author
    description: The author of this git commit
  - name: git-branch
    description: The name of the git branch
  - name: git-repo
    description: The git repo URL
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: build-image-$(tt.params.image-name)-based-on-$(tt.params.base-template)-
    spec:
      # taskRunSpecs:
      #   - pipelineTaskName: copy-template
      #     taskServiceAccountName: copy-template-task
      #   - pipelineTaskName: create-vm-from-template
      #     taskServiceAccountName: create-vm-from-template-task
      #   - pipelineTaskName: stop-vm
      #     taskServiceAccountName: cleanup-vm-task
      #   - pipelineTaskName: customise-vm
      #     taskServiceAccountName: disk-virt-customize-task
      #   - pipelineTaskName: sysprep-vm
      #     taskServiceAccountName: disk-virt-sysprep-task
      taskRunTemplate:
        serviceAccountName: pipeline
      pipelineRef:
        name: build-image
      params:
      - name: image-name
        value: $(tt.params.image-name)
      # - name: author
      #   value: $(tt.params.author)
      - name: base-template
        value: $(tt.params.base-template)
      workspaces:
        - name: ssh-creds
          secret:
            secretName: argocd-github-ssh
        - name: working-directory
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
