---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Image Build"
    openshift.io/display-name: "Image Build"
  labels:
    argocd.argoproj.io/managed-by: "openshift-gitops"
    openshift.io/cluster-monitoring: "true"
  name: image-build